FROM --platform=linux/amd64 mcr.microsoft.com/azure-functions/python:4-python3.10

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

WORKDIR /home/site/wwwroot

COPY . .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
